quarkus:
  banner:
    enabled: false
  application:
    name: api-service-point
  http:
    port: 8080
  datasource:
    db-kind: postgresql
  hibernate-orm:
    schema-management:
      strategy: none
  flyway:
    migrate-at-start: true
    locations: db/migration
  oidc:
    client-id: ${OIDC_CLIENT_ID:api-service-point}
  smallrye-openapi:
    security-scheme: jwt
    security-scheme-name: bearer

app:
  role-mapping:
    centerpoint-service-point-admin: admin
    centerpoint-service-point-user: user
    exarep-service-point-admin: admin

mp:
  messaging:
    outgoing:
      service-point-events:
        connector: smallrye-kafka
        topic: service-point-events
        value:
          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer

"%dev":
  quarkus:
    hibernate-orm:
      log:
        sql: true
    flyway:
      locations: db/migration,db/testdata
    datasource:
      devservices:
        image-name: registry.access.redhat.com/hi/postgresql:18
        port: 5431
    oidc:
      devservices:
        enabled: true

"%test":
  quarkus:
    flyway:
      locations: db/migration,db/testdata

"%prod":
  kafka:
    bootstrap:
      servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  quarkus:
    oidc:
      auth-server-url: ${OIDC_AUTH_SERVER_URL:http://localhost:8180/realms/ossrep}
    datasource:
      jdbc:
        url: ${DATASOURCE_JDBC_URL:jdbc:postgresql://localhost:5432/servicepoint}
      username: ${DATASOURCE_USERNAME:servicepoint}
      password: ${DATASOURCE_PASSWORD:servicepoint}
    flyway:
      locations: db/migration
